In [2]:
import numpy as np
from random import shuffle

In [47]:
alfabet = ["A", "B", "C", "D", "E", "F"]
indeces = list(range(len(alfabet)))
print(alfabet)
print(indeces)

for _ in range(10):
    shuf = list(range(len(alfabet)))
    shuffle(shuf)
    indeces = [indeces[idx] for idx in shuf]
    alfabet = [alfabet[idx] for idx in shuf]
    print(indeces)
    print(alfabet)

inverse = [0] * len(indeces)
for idx, i in enumerate(indeces):
    inverse[i] = idx
alfabet = [alfabet[idx] for idx in inverse]
print("")
print(alfabet)

['A', 'B', 'C', 'D', 'E', 'F']
[0, 1, 2, 3, 4, 5]
[5, 2, 3, 4, 0, 1]
['F', 'C', 'D', 'E', 'A', 'B']
[2, 1, 5, 3, 0, 4]
['C', 'B', 'F', 'D', 'A', 'E']
[5, 3, 0, 1, 4, 2]
['F', 'D', 'A', 'B', 'E', 'C']
[2, 5, 3, 4, 1, 0]
['C', 'F', 'D', 'E', 'B', 'A']
[5, 3, 0, 2, 1, 4]
['F', 'D', 'A', 'C', 'B', 'E']
[3, 4, 2, 1, 5, 0]
['D', 'E', 'C', 'B', 'F', 'A']
[5, 3, 1, 0, 2, 4]
['F', 'D', 'B', 'A', 'C', 'E']
[5, 2, 1, 4, 0, 3]
['F', 'C', 'B', 'E', 'A', 'D']
[0, 1, 5, 3, 2, 4]
['A', 'B', 'F', 'D', 'C', 'E']
[2, 5, 1, 3, 4, 0]
['C', 'F', 'B', 'D', 'E', 'A']

['A', 'B', 'C', 'D', 'E', 'F']


In [59]:
rewards = np.array([0.1,0.2,0.3,0.4,0.7,1.0])
rewards_copy = rewards.copy()
r_len = len(rewards)
mat = np.random.random([r_len, r_len])
mat_copy = mat.copy()

indeces = np.arange(r_len)
print(rewards)
print(mat)
print(indeces)

for _ in range(3):
    shuf = np.arange(r_len)
    shuffle(shuf)
    rewards = rewards[shuf]
    mat = mat[:, shuf]
    mat = mat[shuf]
    indeces = indeces[shuf]
    print(np.all(rewards == rewards_copy))
    print(np.all(mat == mat_copy))
    print(indeces)

inverse = np.zeros_like(indeces)
inverse[indeces] = np.arange(len(indeces))

rewards = rewards[inverse]
mat = mat[:, inverse]
mat = mat[inverse]

print(rewards)
print(mat)

print(np.all(rewards == rewards_copy))
print(np.all(mat == mat_copy))


[0.1 0.2 0.3 0.4 0.7 1. ]
[[0.59596823 0.17813727 0.67504111 0.79687057 0.05458265 0.3538178 ]
 [0.49793025 0.28442872 0.43668906 0.3629688  0.40085184 0.11605405]
 [0.19120502 0.16341614 0.92909822 0.9486906  0.40226857 0.21183861]
 [0.69179639 0.50489819 0.10616782 0.32215554 0.0115066  0.60398278]
 [0.51733534 0.20436075 0.54955565 0.93009466 0.89721025 0.6005927 ]
 [0.33214047 0.96144044 0.34112431 0.78707445 0.30362298 0.19639859]]
[0 1 2 3 4 5]
False
False
[0 3 5 4 1 2]
False
False
[3 2 4 5 1 0]
False
False
[3 5 1 0 4 2]
[0.1 0.2 0.3 0.4 0.7 1. ]
[[0.59596823 0.17813727 0.67504111 0.79687057 0.05458265 0.3538178 ]
 [0.49793025 0.28442872 0.43668906 0.3629688  0.40085184 0.11605405]
 [0.19120502 0.16341614 0.92909822 0.9486906  0.40226857 0.21183861]
 [0.69179639 0.50489819 0.10616782 0.32215554 0.0115066  0.60398278]
 [0.51733534 0.20436075 0.54955565 0.93009466 0.89721025 0.6005927 ]
 [0.33214047 0.96144044 0.34112431 0.78707445 0.30362298 0.19639859]]
True
True


In [ ]:
---EPOCH-0--------------------
||||| Loss: 0
||||| Loss: 0.4082576600568634
||||| Loss: 0.086722223734369
||||| Loss: 0.0855353536989008
||||| Loss: 0.05949955900544174
||||| Loss: 0.04719025692769458
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.7813265631274915, buffer size: 932
[-15. -15.]
[[ 0 15]
 [15  0]]
---EPOCH-1--------------------
||||| Loss: 0.028808321017358043
||||| Loss: 0.029155270462589623
||||| Loss: 0.02842843008452449
||||| Loss: 0.025095103224978252
||||| Loss: 0.023517931704051215
||||| Loss: 0.018774254925850505
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.6792218140421988, buffer size: 1922
[-13. -17.]
[[ 0 17]
 [13  0]]
---EPOCH-2--------------------
||||| Loss: 0.01631167583193973
||||| Loss: 0.015690602629178475
||||| Loss: 0.01648481516167523
||||| Loss: 0.013721719872972646
||||| Loss: 0.012428193524675937
||||| Loss: 0.011546326117016947
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.5913725020097966, buffer size: 2773
[-16. -14.]
[[ 0 14]
 [16  0]]
---EPOCH-3--------------------
||||| Loss: 0.014669869065236965
||||| Loss: 0.011887523034180444
||||| Loss: 0.013283365499721003
||||| Loss: 0.01304861630735375
||||| Loss: 0.012310494598391102
||||| Loss: 0.012336397145620799
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.5157883426665362, buffer size: 3737
[-14. -16.]
[[ 0 16]
 [14  0]]
---EPOCH-4--------------------
||||| Loss: 0.011888533038483268
||||| Loss: 0.01146874252001043
||||| Loss: 0.01237872256024275
||||| Loss: 0.01126740365534237
||||| Loss: 0.011217795377441128
||||| Loss: 0.012121937015501686
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.4507569268084334, buffer size: 4673
[-12. -18.]
[[ 0 18]
 [12  0]]
---EPOCH-5--------------------
||||| Loss: 0.010601033230085637
||||| Loss: 0.010309351508168535
||||| Loss: 0.010878491833806037
||||| Loss: 0.011621170637154623
||||| Loss: 0.011357035360645591
||||| Loss: 0.01096036244224716
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.394804924626291, buffer size: 5584
[-12. -18.]
[[ 0 18]
 [12  0]]
---EPOCH-6--------------------
||||| Loss: 0.009751188147694196
||||| Loss: 0.009904052988498757
||||| Loss: 0.010664700167686786
||||| Loss: 0.00942989607757461
||||| Loss: 0.009347026876639582
||||| Loss: 0.009072100821261602
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.34666470644279906, buffer size: 6572
[-11. -19.]
[[ 0 19]
 [11  0]]
---EPOCH-7--------------------
||||| Loss: 0.0087635844381007
||||| Loss: 0.008827649964506076
||||| Loss: 0.008179554942688794
||||| Loss: 0.008677028563260194
||||| Loss: 0.009335604013858346
|||TODO: fix bug
|| Loss: 0.008300116481144489
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.30524562372239833, buffer size: 7464
[-12. -18.]
[[ 0 18]
 [12  0]]
---EPOCH-8--------------------
||||| Loss: 0.00836426158023712
||||| Loss: 0.008207060136767324
||||| Loss: 0.008954252604820322
||||| Loss: 0.008775203803472305
||||| Loss: 0.008562324948760929
||||| Loss: 0.007618948860458801
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.26960929970615866, buffer size: 8570
[-12. -18.]
[[ 0 18]
 [12  0]]
---EPOCH-9--------------------
||||| Loss: 0.007171190122543777
||||| Loss: 0.006842462982526641
||||| Loss: 0.00668651230941795
||||| Loss: 0.007133403948197764
||||| Loss: 0.00713651123922318
||||| Loss: 0.0069213944952935
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.23894836986463586, buffer size: 9655
[-14. -16.]
[[ 0 16]
 [14  0]]
---EPOCH-10--------------------
||||| Loss: 0.007202202255988646
||||| Loss: 0.00673488454833146
||||| Loss: 0.006066858820932014
||||| Loss: 0.0065927265071603494
||||| Loss: 0.006714940788536267
||||| Loss: 0.005928274102802025
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.2125681905195841, buffer size: 10000
[ -7. -23.]
[[ 0 23]
 [ 7  0]]
---EPOCH-11--------------------
||||| Loss: 0.005598849949170969
|||TODO: fix bug
|| Loss: 0.005567262727392679
||||| Loss: 0.005324226707316838
||||| Loss: 0.004993477478230267
||||| Loss: 0.0051292603322042095
||||| Loss: 0.005029220857331295
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.18987110123122708, buffer size: 10000
[ -7. -23.]
[[ 0 23]
 [ 7  0]]
---EPOCH-12--------------------
||||| Loss: 0.005011673760470315
||||| Loss: 0.004781836244339113
||||| Loss: 0.0048564050526868924
||||| Loss: 0.004719977709657152
||||| Loss: 0.004795921184171836
||||| Loss: 0.0046905759364987455
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.17034288440504827, buffer size: 10000
[-16. -14.]
[[ 0 14]
 [16  0]]
---EPOCH-13--------------------
||||| Loss: 0.004503056913289047
||||| Loss: 0.00461432434290711
||||| Loss: 0.004342326449464361
||||| Loss: 0.004501128511399214
||||| Loss: 0.004000316229444199
||||| Loss: 0.004061493098250246
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.15354111535152115, buffer size: 10000
[-11. -18.]
[[154  18]
 [165   0]]
---EPOCH-14--------------------
||||| Loss: 0.0036677333294354683
||||| Loss: 0.003771138672305682
||||| Loss: 0.003706362295067971
||||| Loss: 0.003616349027345605
||||| Loss: 0.0034903535846176866
||||| Loss: 0.0041720070892349885
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.1390851388616648, buffer size: 10000
[ -9. -21.]
[[ 0 21]
 [ 9  0]]
---EPOCH-15--------------------
||||| Loss: 0.0030373297402114022
||||| Loss: 0.0028401427017995203
||||| Loss: 0.002881235951795715
||||| Loss: 0.002539021054048848
||||| Loss: 0.0028622432623995266
||||| Loss: 0.002582640117362535
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.12664744521110186, buffer size: 10000
[ -9. -21.]
[[ 0 21]
 [ 9  0]]
---EPOCH-16--------------------
||||| Loss: 0.0027605908472872697
||||| Loss: 0.0026823307961206305
||||| Loss: 0.002270550536795182
||||| Loss: 0.002313449754548065
||||| Loss: 0.002143181525670666
||||| Loss: 0.002093040691037732
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.11594625021027981, buffer size: 10000
[-20.  -9.]
[[  0 225]
 [ 20 216]]
---EPOCH-17--------------------
||||| Loss: 0.0019717296572238883
||||| Loss: 0.002006980384874918
||||| Loss: 0.001816376117031641
||||| Loss: 0.0018860343314537945
||||| Loss: 0.0017182686769956492
||||| Loss: 0.0016222220083946372
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.10673911119697593, buffer size: 10000
[-12. -18.]
[[ 0 18]
 [12  0]]
---EPOCH-18--------------------
||||| Loss: 0.0015280414699919678
||||| Loss: 0.001513886519103305
||||| Loss: 0.0013084767228552221
||||| Loss: 0.0012492755100735132
||||| Loss: 0.001221176101969582
||||| Loss: 0.0011055200618025895
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.09881743433716822, buffer size: 10000
[ -9. -21.]
[[ 0 21]
 [ 9  0]]
---EPOCH-19--------------------
||||| Loss: 0.0010192305372073874
||||| Loss: 0.0010203953120815617
||||| Loss: 0.0009987024168760777
||||| Loss: 0.0009467738323703248
||||| Loss: 0.0009536060749599197
||||| Loss: 0.0009170447228090711
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.09200174879353326, buffer size: 10000
[-13. -17.]
[[ 0 17]
 [13  0]]
---EPOCH-20--------------------
||||| Loss: 0.0008456034103852359
||||| Loss: 0.0008267128289056315
||||| Loss: 0.0007750209817968779
||||| Loss: 0.0007566728616049889
||||| Loss: 0.0007789261711049616
||TODO: fix bug
||| Loss: 0.0007208626993815415
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.0861376406947282, buffer size: 10000
[-14. -16.]
[[ 0 16]
 [14  0]]
---EPOCH-21--------------------
||||| Loss: 0.0006654113456455019
||||| Loss: 0.0006132706780644027
||||| Loss: 0.0005862113832678221
||||| Loss: 0.0005680551235231436
||||| Loss: 0.0005888316178849586
||||| Loss: 0.0005451334990714303
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.08109225478683736, buffer size: 10000
[-18. -12.]
[[ 0 12]
 [18  0]]
---EPOCH-22--------------------
||||| Loss: 0.0005333235056122997
||||| Loss: 0.0005104471289417813
||||| Loss: 0.0005469335277060355
||||| Loss: 0.0005085248549535046
||||| Loss: 0.00054858389333543
||||| Loss: 0.0005032957558149185
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.0767512845095789, buffer size: 10000
[ -8. -21.]
[[  0 224]
 [  8 203]]
---EPOCH-23--------------------
||||| Loss: 0.0004849586674740322
||||| Loss: 0.0004523229325341035
||||| Loss: 0.00047018503941744844
||||| Loss: 0.0004342145101483247
||||| Loss: 0.0004226465485511913
||||| Loss: 0.00041844772116477277
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.07301638230545417, buffer size: 10000
[-15. -15.]
[[ 0 15]
 [15  0]]
---EPOCH-24--------------------
||||| Loss: 0.0003864811307644135
||||| Loss: 0.00042748949256959825
||||| Loss: 0.00039636069556491784
||||| Loss: 0.0004292162276246457
||||| Loss: 0.0003821261297697711
||||| Loss: 0.00039556775637147754
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.06980293149067791, buffer size: 10000
[-14. -16.]
[[ 0 16]
 [14  0]]
---EPOCH-25--------------------
||||| Loss: 0.0003721011933600886
||||| Loss: 0.00036413641619176864
||||| Loss: 0.0003652775705862515
||||| Loss: 0.00035451126108562367
||||| Loss: 0.0003401369288885627
||||| Loss: 0.0003285892974500629
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx Epsilon: 0.06703812920814896, buffer size: 10000
[-12. -18.]
[[ 0 18]
 [12  0]]