In [2]:
from ekenv import EKGame
import numpy as np

In [21]:
history = np.random.randint(0, 10, [4, 15]).astype("float64")
print(history)

[[8. 4. 2. 8. 0. 0. 1. 8. 8. 5. 3. 8. 1. 9. 5.]
 [8. 6. 3. 9. 8. 8. 8. 0. 7. 0. 9. 3. 9. 4. 9.]
 [8. 3. 7. 5. 1. 9. 4. 3. 1. 7. 1. 7. 5. 4. 3.]
 [5. 0. 4. 3. 3. 2. 4. 5. 9. 5. 7. 1. 5. 2. 9.]]


In [22]:
actions = np.random.randint(0, 10, [3, 15]).astype("float64") / 10
print(actions)

[[0.9 0.5 0.9 0.1 0.6 0.5 0.9 0.4 0.7 0.3 0.6 0.3 0.7 0.7 0.7]
 [0.  0.2 0.7 0.  0.8 0.  0.9 0.  0.2 0.1 0.1 0.  0.8 0.2 0.6]
 [0.9 0.5 0.1 0.3 0.  0.2 0.8 0.2 0.4 0.7 0.1 0.3 0.7 0.4 0.3]]


In [23]:
history = np.expand_dims(history, 0)
print(history.shape)

(1, 4, 15)


In [24]:
actions = np.expand_dims(actions, 1)
print(actions.shape)

(3, 1, 15)


In [26]:
history = np.repeat(history, 3, axis=0)
print(history.shape)

(3, 4, 15)


In [27]:
batch = np.concatenate([actions, history], axis = 1)
print(batch.shape)

(3, 5, 15)


In [29]:
x = np.random.randint(0, 10, 10)
print(x)

print(np.argmax(x))

[6 7 1 1 7 9 4 9 5 4]
5
